/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as CorsoRouteImport } from './routes/corso'
import { Route as AttestatoRouteImport } from './routes/attestato'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsoRoute = CorsoRouteImport.update({
  id: '/corso',
  path: '/corso',
  getParentRoute: () => rootRouteImport,
} as any)
const AttestatoRoute = AttestatoRouteImport.update({
  id: '/attestato',
  path: '/attestato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attestato': typeof AttestatoRoute
  '/corso': typeof CorsoRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attestato': typeof AttestatoRoute
  '/corso': typeof CorsoRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attestato': typeof AttestatoRoute
  '/corso': typeof CorsoRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attestato' | '/corso' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attestato' | '/corso' | '/test'
  id: '__root__' | '/' | '/attestato' | '/corso' | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttestatoRoute: typeof AttestatoRoute
  CorsoRoute: typeof CorsoRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corso': {
      id: '/corso'
      path: '/corso'
      fullPath: '/corso'
      preLoaderRoute: typeof CorsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attestato': {
      id: '/attestato'
      path: '/attestato'
      fullPath: '/attestato'
      preLoaderRoute: typeof AttestatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttestatoRoute: AttestatoRoute,
  CorsoRoute: CorsoRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
