/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as DatiAttestatoRouteImport } from './routes/dati-attestato'
import { Route as CorsoRouteImport } from './routes/corso'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttivazioneRouteImport } from './routes/attivazione'
import { Route as AttestatoRouteImport } from './routes/attestato'
import { Route as AccessoRouteImport } from './routes/accesso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthVerificaRouteImport } from './routes/auth.verifica'
import { Route as AccessoVerificaRouteImport } from './routes/accesso.verifica'
import { Route as AccessoSuccessoRouteImport } from './routes/accesso.successo'
import { Route as AccessoAttivaRouteImport } from './routes/accesso.attiva'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DatiAttestatoRoute = DatiAttestatoRouteImport.update({
  id: '/dati-attestato',
  path: '/dati-attestato',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsoRoute = CorsoRouteImport.update({
  id: '/corso',
  path: '/corso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivazioneRoute = AttivazioneRouteImport.update({
  id: '/attivazione',
  path: '/attivazione',
  getParentRoute: () => rootRouteImport,
} as any)
const AttestatoRoute = AttestatoRouteImport.update({
  id: '/attestato',
  path: '/attestato',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoRoute = AccessoRouteImport.update({
  id: '/accesso',
  path: '/accesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerificaRoute = AuthVerificaRouteImport.update({
  id: '/verifica',
  path: '/verifica',
  getParentRoute: () => AuthRoute,
} as any)
const AccessoVerificaRoute = AccessoVerificaRouteImport.update({
  id: '/verifica',
  path: '/verifica',
  getParentRoute: () => AccessoRoute,
} as any)
const AccessoSuccessoRoute = AccessoSuccessoRouteImport.update({
  id: '/successo',
  path: '/successo',
  getParentRoute: () => AccessoRoute,
} as any)
const AccessoAttivaRoute = AccessoAttivaRouteImport.update({
  id: '/attiva',
  path: '/attiva',
  getParentRoute: () => AccessoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRouteWithChildren
  '/attestato': typeof AttestatoRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRouteWithChildren
  '/corso': typeof CorsoRoute
  '/dati-attestato': typeof DatiAttestatoRoute
  '/test': typeof TestRoute
  '/accesso/attiva': typeof AccessoAttivaRoute
  '/accesso/successo': typeof AccessoSuccessoRoute
  '/accesso/verifica': typeof AccessoVerificaRoute
  '/auth/verifica': typeof AuthVerificaRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRouteWithChildren
  '/attestato': typeof AttestatoRoute
  '/attivazione': typeof AttivazioneRoute
  '/corso': typeof CorsoRoute
  '/dati-attestato': typeof DatiAttestatoRoute
  '/test': typeof TestRoute
  '/accesso/attiva': typeof AccessoAttivaRoute
  '/accesso/successo': typeof AccessoSuccessoRoute
  '/accesso/verifica': typeof AccessoVerificaRoute
  '/auth/verifica': typeof AuthVerificaRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRouteWithChildren
  '/attestato': typeof AttestatoRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRouteWithChildren
  '/corso': typeof CorsoRoute
  '/dati-attestato': typeof DatiAttestatoRoute
  '/test': typeof TestRoute
  '/accesso/attiva': typeof AccessoAttivaRoute
  '/accesso/successo': typeof AccessoSuccessoRoute
  '/accesso/verifica': typeof AccessoVerificaRoute
  '/auth/verifica': typeof AuthVerificaRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesso'
    | '/attestato'
    | '/attivazione'
    | '/auth'
    | '/corso'
    | '/dati-attestato'
    | '/test'
    | '/accesso/attiva'
    | '/accesso/successo'
    | '/accesso/verifica'
    | '/auth/verifica'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesso'
    | '/attestato'
    | '/attivazione'
    | '/corso'
    | '/dati-attestato'
    | '/test'
    | '/accesso/attiva'
    | '/accesso/successo'
    | '/accesso/verifica'
    | '/auth/verifica'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/accesso'
    | '/attestato'
    | '/attivazione'
    | '/auth'
    | '/corso'
    | '/dati-attestato'
    | '/test'
    | '/accesso/attiva'
    | '/accesso/successo'
    | '/accesso/verifica'
    | '/auth/verifica'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoRoute: typeof AccessoRouteWithChildren
  AttestatoRoute: typeof AttestatoRoute
  AttivazioneRoute: typeof AttivazioneRoute
  AuthRoute: typeof AuthRouteWithChildren
  CorsoRoute: typeof CorsoRoute
  DatiAttestatoRoute: typeof DatiAttestatoRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dati-attestato': {
      id: '/dati-attestato'
      path: '/dati-attestato'
      fullPath: '/dati-attestato'
      preLoaderRoute: typeof DatiAttestatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corso': {
      id: '/corso'
      path: '/corso'
      fullPath: '/corso'
      preLoaderRoute: typeof CorsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivazione': {
      id: '/attivazione'
      path: '/attivazione'
      fullPath: '/attivazione'
      preLoaderRoute: typeof AttivazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attestato': {
      id: '/attestato'
      path: '/attestato'
      fullPath: '/attestato'
      preLoaderRoute: typeof AttestatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesso': {
      id: '/accesso'
      path: '/accesso'
      fullPath: '/accesso'
      preLoaderRoute: typeof AccessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verifica': {
      id: '/auth/verifica'
      path: '/verifica'
      fullPath: '/auth/verifica'
      preLoaderRoute: typeof AuthVerificaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/accesso/verifica': {
      id: '/accesso/verifica'
      path: '/verifica'
      fullPath: '/accesso/verifica'
      preLoaderRoute: typeof AccessoVerificaRouteImport
      parentRoute: typeof AccessoRoute
    }
    '/accesso/successo': {
      id: '/accesso/successo'
      path: '/successo'
      fullPath: '/accesso/successo'
      preLoaderRoute: typeof AccessoSuccessoRouteImport
      parentRoute: typeof AccessoRoute
    }
    '/accesso/attiva': {
      id: '/accesso/attiva'
      path: '/attiva'
      fullPath: '/accesso/attiva'
      preLoaderRoute: typeof AccessoAttivaRouteImport
      parentRoute: typeof AccessoRoute
    }
  }
}

interface AccessoRouteChildren {
  AccessoAttivaRoute: typeof AccessoAttivaRoute
  AccessoSuccessoRoute: typeof AccessoSuccessoRoute
  AccessoVerificaRoute: typeof AccessoVerificaRoute
}

const AccessoRouteChildren: AccessoRouteChildren = {
  AccessoAttivaRoute: AccessoAttivaRoute,
  AccessoSuccessoRoute: AccessoSuccessoRoute,
  AccessoVerificaRoute: AccessoVerificaRoute,
}

const AccessoRouteWithChildren =
  AccessoRoute._addFileChildren(AccessoRouteChildren)

interface AuthRouteChildren {
  AuthVerificaRoute: typeof AuthVerificaRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerificaRoute: AuthVerificaRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoRoute: AccessoRouteWithChildren,
  AttestatoRoute: AttestatoRoute,
  AttivazioneRoute: AttivazioneRoute,
  AuthRoute: AuthRouteWithChildren,
  CorsoRoute: CorsoRoute,
  DatiAttestatoRoute: DatiAttestatoRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
